version: 0.2

phases:  

  pre_build:
    commands:
      - cd /efs
      - docker build -t dockertest .
      
  build:
    commands:
      - cd /efs
      - docker run dockertest
      - docker save -o dockertest.tar dockertest
      - ls

  post_build:
    commands:
      - echo "Sono in Post Build"
