version: 0.2

phases:
      
  pre_build:
    commands:
      -  apt-get install zip
      -  apt-get install unzip
      -  apt-get install libncurses5
      
  build:
    commands:
      - source build/envsetup.sh
      - lunch rpi4-eng
      - make ramdisk systemimage vendorimage -j8

  post_build:
    commands:
      - echo "Sono in Post Build"
